[project]
name = "supabase-updater"
version = "0.1.0"
description = "Atualiza a base Supabase com os dados de recomendação"
authors = [
    { name = "Seu Nome", email = "seu@email.com" }
]
dependencies = []
requires-python = ">=3.9"
